#ifndef SHIM4_H
#define SHIM4_H

#include "shim4/a_star.h"
#include "shim4/achievements.h"
#include "shim4/audio.h"
#include "shim4/cd.h"
#include "shim4/cloud.h"
#include "shim4/cpa.h"
#include "shim4/error.h"
#include "shim4/gfx.h"
#include "shim4/gui.h"
#include "shim4/image.h"
#include "shim4/input.h"
#include "shim4/interp.h"
#include "shim4/json.h"
#include "shim4/main.h"
#include "shim4/md5.h"
#include "shim4/mml.h"
#include "shim4/mt.h"
#include "shim4/model.h"
#include "shim4/pixel_font.h"
#include "shim4/primitives.h"
#include "shim4/sample.h"
#include "shim4/shim.h"
#include "shim4/shader.h"
#include "shim4/sprite.h"
#include "shim4/tilemap.h"
#include "shim4/tokenizer.h"
#include "shim4/translation.h"
#ifdef USE_TTF
#include "shim4/ttf.h"
#endif
#include "shim4/utf8.h"
#include "shim4/util.h"
#include "shim4/vertex_cache.h"
#include "shim4/vorbis.h"
//#include "shim4/xml.h"

#endif // SHIM4_H
