var number joy_x1
var number joy_y1
var number joy_x2
var number joy_y2
var number joy_x3
var number joy_y3
var number joy_l
var number joy_r
var number joy_u
var number joy_d
var number joy_a
var number joy_b
var number joy_x
var number joy_y
var number joy_lb
var number joy_rb
var number joy_ls
var number joy_rs
var number joy_back
var number joy_start

joystick_poll 0 joy_x1 joy_y1 joy_x2 joy_y2 joy_x3 joy_y3 joy_l joy_r joy_u joy_d joy_a joy_b joy_x joy_y joy_lb joy_rb joy_ls joy_rs joy_back joy_start
