number joy_x1
number joy_y1
number joy_x2
number joy_y2
number joy_x3
number joy_y3
number joy_l
number joy_r
number joy_u
number joy_d
number joy_a
number joy_b
number joy_x
number joy_y
number joy_lb
number joy_rb
number joy_ls
number joy_rs
number joy_back
number joy_start

joystick_poll 0 joy_x1 joy_y1 joy_x2 joy_y2 joy_x3 joy_y3 joy_l joy_r joy_u joy_d joy_a joy_b joy_x joy_y joy_lb joy_rb joy_ls joy_rs joy_back joy_start
